[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]

it('en: 4 态启动检测行英文', () => {
  applyLang('en');
  expect(installCheckMessage('D:/x', 'unset')).toBe('[lms_launcher] Startup check · llama.cpp directory not set');
  expect(installCheckMessage('D:/x', 'dir_missing')).toBe('[lms_launcher] Startup check · llama.cpp directory does not exist: D:/x');
  expect(installCheckMessage('D:/x', 'exe_missing')).toBe('[lms_launcher] Startup check · llama-server.exe not found in directory: D:/x');
  expect(installCheckMessage('D:/x', 'ok')).toBe('[lms_launcher] Startup check · llama-server.exe available: D:/x');
  applyLang('zh');
});