// src-main/update-bootstrap.ts
// 更新启动器（bootstrap）生成。计划任务 /TR 有 261 字符上限（main.ts:569 的 2026-09-05 复盘），
// ps1/zip/installDir 三个绝对参数必须经安装目录里的一个短启动器文件中转；本模块生成它并给出 /TR 值。
// 2026-10-08：默认生成 .vbs —— wscript + sh.Run(cmd, 0, True) 实测全程 0 个新增可见控制台窗口（口径见规格 H2）；
// 原先的 .cmd 实测新增 1 个可见顶层窗口（hwnd 口径；旧探针按 class+title+pid 去重会记成 2 条；
// 默认控制台宿主是 Windows Terminal）。
// wscript.exe 缺失（Win11 已把 WSH 列为可选组件）→ 回退 .cmd：会出现可见窗口，但更新照常完成。
// 规格：docs/superpowers/specs/2026-10-08-hidden-update-launcher-design.md
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const BOOTSTRAP_VBS_NAME = 'lms_launcher_update.vbs';
export const BOOTSTRAP_CMD_NAME = 'lms_launcher_update.cmd';

export interface BootstrapInput {
  installDir: string;
  wscriptPath: string;
  ps1Path: string;
  zipPath: string;
  updateLogPath: string;
}

export interface BootstrapPlan {
  kind: 'vbs' | 'cmd';
  filePath: string;
  /** 放进 schtasks /TR "…" 里的内容；内部双引号已按 CommandLineToArgvW 规则转义（规格 H8）。 */
  trValue: string;
  /** true = 回退到可见窗口的 .cmd，调用方需记一条降级日志。 */
  degraded: boolean;
}

// VBScript 里表示一个双引号要写 4 个引号，少写一个就是「未结束的字符串常量」（800A0409），
// 而 WSH 的编译错误弹窗本身就是一个可见窗口（2026-10-08 实测）。引号一律由 Chr(34) 提供。
// 路径直接写进 VBScript 字符串字面量：Windows 路径不可能含双引号，含 & 空格中文均安全。
export function vbsContent(i: BootstrapInput): string {
  return [
    "' LMS Launcher update bootstrapper - generated by the app before every update, do not edit.",
    "' Starts the update script with a hidden console (window style 0 = SW_HIDE) and waits for it.",
    "' Quotes come from Chr(34) on purpose: a VBScript quote-literal mistake is a compile error,",
    "' and WSH would answer it with a modal error dialog - the visible window this file removes.",
    'Option Explicit',
    'Dim sh, fso, ts, cmd, rc, q, n, stamp',
    "' The guard must precede the first statement that can raise: with no guard active a raising",
    "' statement aborts the script - no log line at all, and the task still reports LastTaskResult=0.",
    'On Error Resume Next',
    'Set sh = CreateObject("WScript.Shell")',
    'q = Chr(34)',
    'cmd = q & "powershell.exe" & q & " -NoProfile -ExecutionPolicy Bypass -File " & q & "' + i.ps1Path + '" & q',
    'cmd = cmd & " " & q & "' + i.zipPath + '" & q & " " & q & "' + i.installDir + '" & q',
    'rc = sh.Run(cmd, 0, True)',
    'If Err.Number <> 0 Then',
    "  ' No WSH error dialog: append to the update log instead; the app replays that log on next start.",
    "  ' Err.Description is written in the system ANSI codepage: it is localized (non-ASCII on a Chinese",
    "  ' Windows) and it can be empty, so Err.Number is logged as well - the number is what survives.",
    '  Set fso = CreateObject("Scripting.FileSystemObject")',
    '  Set ts = fso.OpenTextFile("' + i.updateLogPath + '", 8, True)',
    '  n = Now',
    '  stamp = Year(n) & "-" & Right("0" & Month(n), 2) & "-" & Right("0" & Day(n), 2)',
    '  stamp = stamp & " " & Right("0" & Hour(n), 2) & ":" & Right("0" & Minute(n), 2) & ":" & Right("0" & Second(n), 2)',
    '  ts.WriteLine stamp & " [ERROR] [vbs] Could not start the update script: " & Err.Description & " number=" & Err.Number',
    '  ts.Close',
    '  WScript.Quit 1',
    'End If',
    'WScript.Quit rc',
    '',
  ].join('\r\n');
}

// 回退启动器：cmd.exe 按当前控制台代码页解码批处理正文，因此在任何路径出现之前先 chcp 65001（本函数生成时在第 4 行、两条 rem 之后；被测试钉住的是顺序不是行号），
// 之后出现的非 ASCII 安装路径才不会被解错（2026-10-08 实测：'ascii' 写法在中文目录下直接失败）。
export function cmdContent(i: BootstrapInput): string {
  return [
    '@echo off',
    'rem LMS Launcher update bootstrapper - fallback used only when wscript.exe is unavailable.',
    'rem A console window is visible with this path; the update itself still completes.',
    'chcp 65001 >nul',
    'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "' + i.ps1Path + '" "' + i.zipPath + '" "' + i.installDir + '"',
    '',
  ].join('\r\n');
}

const quote = (s: string): string => '"' + s + '"';
// 不用 /"/g 这样的正则字面量：i18n 守护（no-hardcoded.test.ts）的扫描器不识别正则，
// 会把其中的双引号当成字符串起点，连带把后面的中文注释读成字面量而误报。
const escapeForTr = (s: string): string => s.split('"').join('\\"');

export function writeUpdateBootstrap(i: BootstrapInput, hasWscript: boolean): BootstrapPlan {
  if (hasWscript) {
    const filePath = join(i.installDir, BOOTSTRAP_VBS_NAME);
    // Node 的 'utf16le' 不写 BOM；WSH 只接受 UTF-16LE（无 BOM 也能解，但 UTF-8 与 UTF-16BE 都不被接受），
    // 显式加 BOM 是被测试钉住的、各方都认的形态。
    writeFileSync(filePath, '\uFEFF' + vbsContent(i), 'utf16le');
    return { kind: 'vbs', filePath, trValue: escapeForTr(quote(i.wscriptPath) + ' ' + quote(filePath)), degraded: false };
  }
  const filePath = join(i.installDir, BOOTSTRAP_CMD_NAME);
  writeFileSync(filePath, cmdContent(i), 'utf8'); // 无 BOM：cmd.exe 会把 BOM 当命令字符
  return { kind: 'cmd', filePath, trValue: escapeForTr(quote(filePath)), degraded: true };
}
